-- phpMyAdmin SQL Dump
-- version 4.0.4.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Sep 15, 2014 at 09:27 PM
-- Server version: 5.6.13
-- PHP Version: 5.4.17

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `microboatdb_example`
--
CREATE DATABASE IF NOT EXISTS `microboatdb_example` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `microboatdb_example`;

-- --------------------------------------------------------

--
-- Table structure for table `jobs`
--

DROP TABLE IF EXISTS `jobs`;
CREATE TABLE IF NOT EXISTS `jobs` (
  `pk_jobs` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(60) NOT NULL,
  `description` varchar(500) NOT NULL,
  `wage` float NOT NULL,
  PRIMARY KEY (`pk_jobs`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=6 ;

--
-- Truncate table before insert `jobs`
--

TRUNCATE TABLE `jobs`;
--
-- Dumping data for table `jobs`
--

INSERT INTO `jobs` (`pk_jobs`, `name`, `description`, `wage`) VALUES
(1, 'Soldier', 'A soldier is one who fights as part of an organized land-based armed force; if that force is for hire the person is generally termed a mercenary soldier, or mercenary. The majority of cognates of the word "soldier" that exist in other languages have a meaning that embraces both commissioned and non-commissioned officers in national land forces.', 10.55),
(2, 'Physician', 'A physician is a professional who practices medicine, which is concerned with promoting, maintaining or restoring human health through the study, diagnosis, and treatment of disease, injury, and other physical and mental impairments. They may focus their practice on certain disease categories, types of patients, or methods of treatment.', 30.22),
(3, 'Painter', 'A house painter and decorator is a tradesman responsible for the painting and decorating of buildings, and is also known as a decorator or house painter. The purpose of painting is to improve the aesthetic of a building and to protect it from damage by water, rust, corrosion, insects and mould.', 8),
(4, 'Whore', 'A person who works in this field is called a prostitute, and is a kind of sex worker. Prostitution is one of the branches of the sex industry. The legal status of prostitution varies from country to country, from being permissible but unregulated, to an enforced or unenforced crime or to a regulated profession. Prostitution is sometimes also referred to as "the world''s oldest profession". Estimates place the annual revenue generated by prostitution worldwide to be over $100 billion.', 5.66),
(5, 'Police', 'A police force is a constituted body of persons empowered by the state to enforce the law, protect property, and limit civil disorder. Their powers include the legitimized use of force. The term is most commonly associated with police services of a state that are authorized to exercise the police power of that state within a defined legal or territorial area of responsibility.', 9.22);

-- --------------------------------------------------------

--
-- Table structure for table `peaple`
--

DROP TABLE IF EXISTS `peaple`;
CREATE TABLE IF NOT EXISTS `peaple` (
  `pk_peaple` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(60) NOT NULL,
  `sirname` varchar(60) NOT NULL,
  `male` tinyint(1) NOT NULL,
  `birthday` date NOT NULL,
  `fk_job` int(11) NOT NULL,
  PRIMARY KEY (`pk_peaple`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=8 ;

--
-- Truncate table before insert `peaple`
--

TRUNCATE TABLE `peaple`;
--
-- Dumping data for table `peaple`
--

INSERT INTO `peaple` (`pk_peaple`, `name`, `sirname`, `male`, `birthday`, `fk_job`) VALUES
(1, 'Kees', 'Appel', 1, '1995-06-09', 1),
(2, 'Jan', 'Kanderwatvan', 1, '1995-04-09', 0),
(3, 'Joop', 'Knoop', 1, '2001-11-12', 3),
(4, 'Ellen', 'Akkerman', 0, '1995-10-16', 2),
(5, 'Henk', 'de Boer', 1, '1995-12-18', 0),
(6, 'Willem', 'de Leeuw', 1, '2001-09-18', 2),
(7, 'Marlijda', 'de Hoop', 0, '2001-09-19', 5);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
